### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by nukeop** [AlynxZhou/gnome-shell-extension-inotch#13]
In the readme it says:

> It covers my clock!

> This is the same behavior as hardware notch. Don't ask Apple to do things for developers, but ask developers to do things for Apple! So write your own code to modify your software.

Only Gnome displays the time in the middle of the taskbar at the top. Macs don't do that, so the notch doesn't cover anything.

**Comment by AlynxZhou** [comment]
> Only Gnome displays the time in the middle of the taskbar at the top.

This is a GNOEM Shell extension.
