### ISSUE TITLE
Please write a port of this for the Common Desktop Environment (CDE) 

### ISSUE THREAD

**Issue by georgeoshardo** [AlynxZhou/gnome-shell-extension-inotch#21]
The [common desktop environment](https://en.wikipedia.org/wiki/Common_Desktop_Environment) was released 30 years ago. If you write a port for this DE, it can be sent back in time, and people in the early days of desktop environments can understand the functionality, utility and superiority of a notch. This will result in more notched devices throughout time, making life better for everyone.

**Comment by AlynxZhou** [comment]
I'm a GNOME dev, not KDE dev or CDE dev, so please work on it if you can.
