### ISSUE TITLE
Portion of mouse can appear on top of the iNotch

### ISSUE THREAD

**Issue by nesper8** [AlynxZhou/gnome-shell-extension-inotch#23]
![Screenshot from 2021-10-30 17-04-36](https://user-images.githubusercontent.com/57890520/139531401-9a628766-0742-4c5d-beb1-83b7e7874d9b.png)
literally unusable

**Comment by AlynxZhou** [comment]
I know this but I can do nothing for it, sorry. You can not show only part of cursor in GNOME Shell (at least you cannot do it easily), maybe buying a Macbook Pro will solve this bug.
